import {
  BookOpen,
  CalendarDays,
  Compass,
  CreditCard,
  History,
  LifeBuoy,
  ListChecks,
  MessageCircle,
  Plug,
  Receipt,
  Send,
  SlidersHorizontal,
  UserRound,
  Users,
  type LucideIcon,
} from "lucide-react";

export const SECTION_ICONS: Record<string, LucideIcon> = {
  start: Compass,
  account: UserRound,
  pay: CreditCard,
  connect: Plug,
  review: History,
  rules: SlidersHorizontal,
  watch: CalendarDays,
  live: Send,
  billing: Receipt,
  team: Users,
  recipes: ListChecks,
  wrong: LifeBuoy,
  reference: BookOpen,
  help: MessageCircle,
};
