import { A, Blockquote, Code, H2, H3, H4, Hr, Li, Ol, P, Strong, Table, Td, Th, Ul } from "./elements";
import { Callout, Example, Figure, Group, InPlainWords, PmsTab, PmsTabs, Related, Step, Steps, Ui } from "./blocks";
import {
  AppTour,
  BookingSpeedPlayground,
  DateStrip,
  FloorLadder,
  MessageFinder,
  OccupancySlider,
  PriceCalculator,
  SentenceBuilder,
  StackingCalculator,
  WaitTimeline,
} from "../widgets";
import { AppLink, OpenInMaya } from "../app-links/server";

/** Every name a docs page may use, and every Markdown element's look. */
export const mdxComponents = {
  h2: H2,
  h3: H3,
  h4: H4,
  p: P,
  a: A,
  ul: Ul,
  ol: Ol,
  li: Li,
  strong: Strong,
  table: Table,
  th: Th,
  td: Td,
  blockquote: Blockquote,
  hr: Hr,
  code: Code,
  InPlainWords,
  Callout,
  Ui,
  Example,
  PmsTabs,
  PmsTab,
  Steps,
  Step,
  Figure,
  Related,
  Group,
  AppLink,
  OpenInMaya,
  OccupancySlider,
  BookingSpeedPlayground,
  StackingCalculator,
  WaitTimeline,
  PriceCalculator,
  FloorLadder,
  SentenceBuilder,
  DateStrip,
  AppTour,
  MessageFinder,
};
